/** Mirrors app/core/permissions.py — keep both lists in step. */
export const PERMISSIONS = {
  dashboardRead: "dashboard:read",
  toolsRead: "tools:read",
  botRead: "bot:read",
  botConnect: "bot:connect",
  botDisconnect: "bot:disconnect",
  customerRead: "customer:read",
  customerUpdate: "customer:update",
  customerSync: "customer:sync",
  messageSend: "message:send",
  mentionRead: "mention:read",
  mentionUpdate: "mention:update",
  mentionPolicyManage: "mention_policy:manage",
  staffManage: "staff:manage",
  mentionBulkApply: "mention_bulk:apply",
  mentionFollowupRead: "mention_followup:read",
  mentionFollowupCancel: "mention_followup:cancel",
  debtReminderRead: "debt_reminder:read",
  debtReminderUpdate: "debt_reminder:update",
  debtReminderBulkApply: "debt_reminder_bulk:apply",
  debtReminderHistoryRead: "debt_reminder_history:read",
  driveConversionManage: "drive_conversion:manage",
  activityRead: "activity:read",
  modelActivityRead: "model_activity:read",
  userRead: "user:read",
  userCreate: "user:create",
  userUpdate: "user:update",
  userDelete: "user:delete",
  roleRead: "role:read",
  roleManage: "role:manage",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
